CREATE TABLE lorcana_cards (
    id              INTEGER PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    title           VARCHAR(255),
    cost            INTEGER,
    inkwell         TINYINT,
    attack          INTEGER,
    defence         INTEGER,
    color           SMALLINT,
    colors          VARCHAR(20),
    type            VARCHAR(50),
    action          TEXT,
    flavour         TEXT,
    separator       VARCHAR(50),
    stars           SMALLINT,
    illustrator     VARCHAR(100),
    card_set_id     INTEGER,
    language        VARCHAR(10),
    number          INTEGER,
    pack            VARCHAR(100),
    rarity          VARCHAR(50),
    image           TEXT,
    blurhash        VARCHAR(255),
    franchise_id    INTEGER,
    final           TINYINT,
    spoiler         TINYINT,
    published       TINYINT,
    created_at      DATETIME,
    updated_at      DATETIME,
    traits          TEXT,
    prices          TEXT
);
CREATE INDEX IF NOT EXISTS idx_lorcana_cards_name ON lorcana_cards(name);
