CREATE TABLE IF NOT EXISTS lorcana_cards (
    id              INTEGER PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    version         VARCHAR(255),
    full_name       VARCHAR(355),
    simple_name     VARCHAR(355),
    cost            INTEGER,
    inkwell         TINYINT,
    strength        INTEGER,
    willpower       INTEGER,
    color           VARCHAR(20),
    type            VARCHAR(50),
    full_text       TEXT,
    flavor_text     TEXT,
    lore            SMALLINT,
    artists         TEXT,
    set_code        VARCHAR(10),
    number          INTEGER,
    rarity          VARCHAR(50),
    image_full      TEXT,
    image_thumbnail TEXT,
    story           VARCHAR(100),
    subtypes        TEXT,
    abilities       TEXT,
    full_identifier VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS idx_lorcana_cards_name ON lorcana_cards(name);
