name: Lorcana MCP CI

on:
  push:
    branches:
      - "**"
      - "!gh-pages"
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --dev
      - name: Test with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          uv run pytest tests
